title = "RuKAV Association"
baseURL = "https://rukav-swiss.ch/"
languageCode = "en-us"
theme = ["ananke"]
resourceDir = "../resources"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
# sectionPagesMenu = "main" # for automatic section creation
pagerSize = 5
googleAnalytics = ""
enableRobotsTXT = true

[languages]

  [languages.en]
    title = "RuKAV"
    weight = 1
    contentDir = "content/en"

    [[languages.en.menu.main]]
      name = "Home"
      url = "/en/"
      weight = 1

    [[languages.en.menu.main]]
      name = "Events"
      url = "/en/events/"
      weight = 2

    [[languages.en.menu.main]]
      name = "Join us"
      url = "/en/join-us/"
      weight = 3

    [[languages.en.menu.main]]
      name = "Board"
      url = "/en/board/"
      weight = 4

    [[languages.en.menu.main]]
      name = "Documents"
      url = "/en/documents/"
      weight = 5

    [[languages.en.menu.main]]
      name = "Contact"
      url = "/en/contact/"
      weight = 6

     [[languages.en.menu.main]]
          name = "📸"
          url = "https://instagram.com/rukav.swiss"
          weight = 90
          #pre = "<i class=\"fab fa-instagram\"></i>"   # optional Font Awesome icon
          params.newtab = true                         # custom param – we’ll use it later

    [[languages.en.menu.main]]
          name = "▶️"
          url = "https://www.youtube.com/@Rukav-Swiss"
          weight = 91
          params.newtab = true                         # custom param – we’ll use it later


  [languages.ru]
    title = "РуКАВ"
    weight = 2
    contentDir = "content/ru"

    [[languages.ru.menu.main]]
      name = "Главная"
      url = "/ru/"
      weight = 1

    [[languages.ru.menu.main]]
      name = "Мероприятия"
      url = "/ru/events/"
      weight = 2

    [[languages.ru.menu.main]]
      name = "Присоединиться"
      url = "/ru/join-us/"
      weight = 3

    [[languages.ru.menu.main]]
      name = "Правление"
      url = "/ru/board/"
      weight = 4

    [[languages.ru.menu.main]]
      name = "Документы"
      url = "/ru/documents/"
      weight = 5

    [[languages.ru.menu.main]]
      name = "Контакты"
      url = "/ru/contact/"
      weight = 6

    [[languages.ru.menu.main]]
      name = "📸"
      url = "https://instagram.com/rukav.swiss"
      weight = 90
      #pre = "<i class=\"fab fa-instagram\"></i>"  # optional Font Awesome icon
      params.newtab = true                         # custom param – we’ll use it later

    [[languages.en.menu.main]]
      name = "▶️"
      url = "https://www.youtube.com/@Rukav-Swiss"
      weight = 91
      params.newtab = true                         # custom param – we’ll use it later


[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = "black" #"white"
author = ""
favicon = "images/rukav_logo_square-transparent.png"
site_logo = "images/rukav_logo_square-transparent.png"
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-blue"
recent_posts_number = 3

custom_css = ["css/custom.css"]

[params.events]
  showUpcoming = true
  maxDisplay = 5
  dateFormat = "2 January, 2006"